name: generate animation

on:
  schedule:
      # every 24 hours
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: kajdev
          svg_out_path: dist/snake.svg
